// export { default as Heading } from './Head/Heading';
export { default as UserIdentifier } from './UserIdentifier/UserIdentifier';
export { default as Post } from './Post/Post';
export { default as PostAuthentic } from './Post/PostAuthentic';
export { default as PostOptions } from './PostOptions/PostOptions';

export { default as OptionsMini } from './OptionsModal/OptionsMini';
export { default as OptionsBig } from './OptionsModal/OptionsBig';
export { default as TextArea } from './TextArea/TextArea';
export { default as TextAreaWithTag } from './TextArea/TextAreaWithTag';
export { default as Modal } from './Modal/Modal';
// export { default as Acordion } from './Acordion/Acordion';
// export { default as Form } from './Form/Form';
// export { default as SelectCountry } from './SelectCountry/SelectCountry';
export { default as SearchBar } from './SearchBar/SearchBar';
export { default as CancelRequestBTN } from './RequestBTN/CancelRequestBTN';
export { default as ConfirmRequestBtn } from './RequestBTN/ConfirmRequestBtn';
export { default as DeleteRequestBTN } from './RequestBTN/DeleteRequestBTN';
export { default as SendRequestBTN } from './RequestBTN/SendRequestBTN';
export { default as SendMessageBTN } from './RequestBTN/SendMessageBTN';
export { default as IsFriendBTN } from './RequestBTN/IsFriendBTN';
export { default as CreatePost } from './CreatePost/CreatePost';
export { default as CreatePostModal } from './CreatePost/CreatePostModal';
export { default as SideBar } from './SideBar/SideBar';
export { default as MultiCarousel } from './MultiCarousel/MultiCarousel';
export { default as BlogLabelsPopUp } from './BlogLabelsPopUp/BlogLabelsPopUp';
export { default as BlogPost } from './BlogPost/BlogPost';
export { default as SwiperSlider } from './SwiperSlider/SwiperSlider';
export { default as CommentsList } from './Comments/CommentsList';
export { default as PostActions } from './PostActions/PostActions';
export { default as DeletionPopUp } from './DeletionPopUp/DeletionPopUp';
