import Head from 'next/head';
import { UserIdentifier, Post, Acordion, SelectCountry, Form } from '../components/Layouts';
import {
  BTN,
  Spinner,
  TimeAgo,
  TimeAgoLong,
  Avatar,
  Input,
  Select,
  DatePicker,
} from '../components/Interface';
import { posts } from '../utils';

export default function Content() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        style={{
          maxWidth: '1140px',
          margin: '0 auto',
          display: 'flex',
          flexDirection: 'column',
          gap: '2rem',
          paddingTop: '4rem',
          paddingBottom: '4rem',
        }}>
        <Spinner />
        <BTN>submit</BTN>
        <Input label='user name' />
        <TimeAgo date={new Date('2022-07-30')} />
        <TimeAgoLong />
        <Acordion />
        <Select />
        <SelectCountry />
        <DatePicker />
        {/* <Form /> */}
        <Avatar />
        <UserIdentifier withTime={false} />
        <UserIdentifier />
        <Post data={posts[0]} />
        <Post data={posts[1]} />
        <Post data={posts[2]} />
      </div>
    </>
  );
}
