export const blogPostText =
  'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque, maiores providentcorrupti eum, natus corporis delectus quas autem quos quaerat quia cumque temporibus laudantium unde tempora officiis eos quam blanditiis.lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit quasi laboriosam ipsa reiciendis eveniet ex et voluptatum magnam dolorum? Odit non dolore cumque. Necessitatibus officiis numquam consequatur quam illum reprehenderit omnis consectetur deleniti adipisci. Error ea illum, minus, tempora fugit accusamus inventore maxime quod dignissimos aliquam commodi delectus? Dolor, nulla! Autem in corrupti illo beatae nesciunt dolore quos, nihil natus quae cupiditate minima quam ut facilis enim eaque deserunt? Quas assumenda voluptates optio rem corrupti, autem repudiandae qui! Eius odio nisi, quaerat placeat autem ipsa reiciendis quas nihil recusandae tempora voluptatibus ex aspernatur adipisci, repellendus veniam rem ab explicabo facere! veniam rem ab explicabo ! dignissimos aliquam commodi delectus? Dolor, nulla! Autem in corrupti illo beatae nesciunt dolore quos, nihil natus quae cupiditate minima quam ut facilis enim eaque deserunt? Quas assumenda voluptates optio rem corrupti, autem repudiandae qui! Eius odio nisi, quaerat placeat autem ipsa reiciendis quas nihil recusandae tempora voluptatibus ex aspernatur adipisci, repellendus veniam rem ab explicabo facere! veniam rem ab explicabo dignissimos aliquam commodi delectus? Dolor, nulla! Autem in corrupti illo beatae nesciunt dolore quos, nihil natus quae cupiditate minima quam ut facilis enim eaque deserunt? Quas assumenda voluptates optio rem corrupti, autem repudiandae qui! Eius odio nisi, quaerat placeat autem ipsa reiciendis quas nihil recusandae tempora voluptatibus ex aspernatur adipisci, repellendus veniam rem ab explicabo facere! veniam rem ab explicabo  minima quam ut facilis enim eaque deserunt? Quas assumenda voluptates optio rem corrupti, autem repudiandae qui! Eius odio nisi sd nesciunt dolore quos, nihil natus quae cupiditate minima quam ut facilis enim eaque deserunt? Quas assumenda voluptates optio rem corrupti, autem repudiandae qui! Eius odio nisi, quaerat placeat autem ipsa reiciendis quas nihil recusandae tempora voluptatibus ex aspernatur adipisci, repellendus veniam rem ab explicabo facere! veniam rem ab explicabo  minima quam ut facilis enim eaque deserunt? Quas assumenda voluptates optio rem corrupti, autem repudiandae qui! Eius odio nisi sd';

const users = [
  {
    _id: '62fbaf941fffa1f725217953',
    firstName: 'john',
    lastName: 'russ',
    userName: 'john russ',
    email: 'russ@io.com',
    createdAt: '2022-08-16T14:54:12.108+00:00',
    img: '/img/user-1.jpg',
    education: [
      {
        collage: 'itvet',
        faculty: 'Web-Interface and Graphical-Design',
        degree: 'bachelor',
        description: 'great 2 year experience',
        years: {
          from: '2019-09-16T00:00:00.000+00:00',
          to: '2021-07-26T00:00:00.000+00:00',
        },
      },
      {
        collage: 'TSU',
        faculty: 'Georgian Philology',
        degree: 'bachelor',
        description: 'great 4 year experience',
        years: {
          from: '2014-09-16T00:00:00.000+00:00',
          to: '2018-07-26T00:00:00.000+00:00',
        },
      },
    ],
    workplace: [
      {
        company: 'devsforworld',
        position: 'frontend-developer',
        description: 'great 3 year experience',
        workingYears: {
          from: '2017-03-13T00:00:00.000+00:00',
          to: '2020-06-16T00:00:00.000+00:00',
        },
      },
      {
        company: 'influencer',
        position: 'sofware-engineer',
        description: 'great 2 year experience',
        workingYears: {
          from: '2020-06-30T00:00:00.000+00:00',
          to: '2022-08-17T00:00:00.000+00:00',
        },
      },
    ],
    birthDate: '1996-02-28T00:00:00.000+00:00',
    from: {
      country: 'georgia',
      city: 'ozurgeti',
    },
    currentLivingPlace: {
      country: 'georgia',
      city: 'tbilisi',
    },
    gender: 'male',
    friends: [
      {
        _id: '63022fd21afbedd194623296',
        userName: 'ross geller',
        profileImg: '/img/user-2.jpg',
      },
    ],
    pendingRequests: [],
    sentRequests: [],
  },
  {
    _id: '63022fd21afbedd194623296',
    firstName: 'ross',
    lastName: 'geller',
    userName: 'ross geller',
    email: 'geller@io.com',
    createdAt: '2022-08-16T14:54:12.108+00:00',
    education: [
      {
        collage: 'itvet',
        faculty: 'Web-Interface and Graphical-Design',
        degree: 'bachelor',
        description: 'great 2 year experience',
        years: {
          from: '2019-09-16T00:00:00.000+00:00',
          to: '2021-07-26T00:00:00.000+00:00',
        },
      },
      {
        collage: 'TSU',
        faculty: 'Georgian Philology',
        degree: 'bachelor',
        description: 'great 4 year experience',
        years: {
          from: '2014-09-16T00:00:00.000+00:00',
          to: '2018-07-26T00:00:00.000+00:00',
        },
      },
    ],
    workplace: [
      {
        company: 'devsforworld',
        position: 'frontend-developer',
        description: 'great 3 year experience',
        workingYears: {
          from: '2017-03-13T00:00:00.000+00:00',
          to: '2020-06-16T00:00:00.000+00:00',
        },
      },
      {
        company: 'influencer',
        position: 'sofware-engineer',
        description: 'great 2 year experience',
        workingYears: {
          from: '2020-06-30T00:00:00.000+00:00',
          to: '2022-08-17T00:00:00.000+00:00',
        },
      },
    ],
    birthDate: '1996-02-28T00:00:00.000+00:00',
    from: {
      country: 'georgia',
      city: 'ozurgeti',
    },
    currentLivingPlace: {
      country: 'georgia',
      city: 'tbilisi',
    },
    gender: 'male',
    friends: [
      {
        _id: '62fbaf941fffa1f725217953',
        userName: 'john russ',
        profileImg: '/img/user-1.jpg',
      },
    ],
    pendingRequests: [],
    sentRequests: [],
    img: '/img/user-2.jpg',
  },
  {
    _id: '63022fd21afbedd194629236',
    firstName: 'rachel',
    lastName: 'green',
    userName: 'rachel green',
    email: 'green@io.com',
    createdAt: '2022-08-16T14:54:12.108+00:00',
    education: [
      {
        collage: 'itvet',
        faculty: 'Web-Interface and Graphical-Design',
        degree: 'bachelor',
        description: 'great 2 year experience',
        years: {
          from: '2019-09-16T00:00:00.000+00:00',
          to: '2021-07-26T00:00:00.000+00:00',
        },
      },
      {
        collage: 'TSU',
        faculty: 'Georgian Philology',
        degree: 'bachelor',
        description: 'great 4 year experience',
        years: {
          from: '2014-09-16T00:00:00.000+00:00',
          to: '2018-07-26T00:00:00.000+00:00',
        },
      },
    ],
    workplace: [
      {
        company: 'devsforworld',
        position: 'frontend-developer',
        description: 'great 3 year experience',
        workingYears: {
          from: '2017-03-13T00:00:00.000+00:00',
          to: '2020-06-16T00:00:00.000+00:00',
        },
      },
      {
        company: 'influencer',
        position: 'sofware-engineer',
        description: 'great 2 year experience',
        workingYears: {
          from: '2020-06-30T00:00:00.000+00:00',
          to: '2022-08-17T00:00:00.000+00:00',
        },
      },
    ],
    birthDate: '1996-02-28T00:00:00.000+00:00',
    from: {
      country: 'georgia',
      city: 'ozurgeti',
    },
    currentLivingPlace: {
      country: 'georgia',
      city: 'tbilisi',
    },
    gender: 'male',
    friends: [],
    pendingRequests: [],
    sentRequests: [],
    img: '/img/user-3.jpg',
  },
];

export const comments = [
  {
    id: 303001,
    text: 'nice umbrella',
    author: users[0],
    createdAt: new Date('2022-08-11'),
    replies: [
      {
        id: 403001,
        text: 'yeap thats wright',
        author: users[1],
        createdAt: new Date('2022-08-10'),
      },
      {
        id: 403002,
        text: 'this is my huge comment reply Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.',
        author: users[0],
        createdAt: new Date('2022-08-09'),
      },
      {
        id: 403003,
        text: 'this one gonna be the pin',
        author: users[2],
        createdAt: new Date('2022-08-08'),
        pin: true,
      },
    ],
  },
  {
    id: 303002,
    text: 'i like you dread',
    author: users[1],
    createdAt: new Date('2022-08-07'),
    pin: true,
    replies: [
      {
        id: 403004,
        text: 'yeap thats wright',
        author: users[2],
        createdAt: new Date('2022-08-10'),
      },
      {
        id: 403005,
        text: 'this is my huge comment reply Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.',
        author: users[0],
        createdAt: new Date('2022-08-09'),
      },
      {
        id: 403006,
        text: 'this one gonna be the pin',
        author: users[1],
        createdAt: new Date('2022-08-08'),
        pin: true,
      },
    ],
  },
  {
    id: 303003,
    text: 'this is my huge comment Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.',
    author: users[2],
    createdAt: new Date('2022-08-06'),
    pin: true,
  },
  // {
  //   id: 303004,
  //   text: 'this is my huge comment Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ipsa corporis itaque vero mollitia obcaecati voluptas eum incidunt voluptates molestiae quia et facere aperiam illo expedita, inventore nemo quo. Blanditiis.',
  //   author: users[2],
  //   createdAt: new Date('2022-08-05'),
  // },
];

export const posts = [
  {
    id: 'post1013443',
    type: 'post',
    author: {
      _id: '62fbaf941fffa1f725217953',
      userName: 'john russ',
      img: '/img/user-1.jpg',
    },
    description:
      '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
    shared: false,
    reactions: [],
    media: ['/img/post-1.jpg'],
    comments: comments,
    createdAt: new Date('2022-07-26'),
  },
  {
    id: 'post1013444',
    type: 'post',
    author: {
      _id: '62fbaf941fffa1f725217953',
      userName: 'ross geller',
      img: '/img/user-2.jpg',
    },
    description: '“Success is not final”',
    media: ['/img/post-1.jpg'],
    shared: true,
    authenticType: 'post',
    authenticAuthor: {
      _id: '62fbaf941fffa1f725217953',
      userName: 'john russ',
      img: '/img/user-1.jpg',
    },
    authenticDateCreation: '2022-08-21T16:04:21.058+00:00',
    authenticDescription:
      '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
    comments: comments,
    reactions: [],
    createdAt: new Date('2022-08-11'),
  },
  {
    id: 'post1013446',
    type: 'post',
    author: {
      _id: '62fbaf941fffa1f725217953',
      userName: 'ross geller',
      img: '/img/user-2.jpg',
    },
    description: 'some description',
    shared: false,
    reactions: [],
    media: ['/img/post-2.jpg', '/img/post-3.jpg'],
    comments: comments,
    createdAt: new Date('2022-07-26'),
  },
  {
    id: 'post1013447',
    type: 'post',
    author: {
      _id: '62fbaf941fffa1f725217953',
      userName: 'john russ',
      img: '/img/user-1.jpg',
    },
    description: 'desc',
    media: ['/img/post-2.jpg', '/img/post-3.jpg'],
    shared: true,
    authenticType: 'post',
    authenticAuthor: {
      _id: '62fbaf941fffa1f725217953',
      userName: 'ross geller',
      img: '/img/user-2.jpg',
    },
    authenticDateCreation: '2022-06-21T16:04:21.058+00:00',
    authenticDescription: 'some description',
    comments: comments,
    reactions: [],
    createdAt: new Date('2022-07-26'),
  },
  // {
  //   type: 'post',
  //   id: 'post1013448',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   description:
  //     '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
  //   media: ['/img/post-1.jpg', '/img/post-2.jpg', '/img/post-3.jpg', '/img/post-4.jpg'],
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  //   shared: true,
  //   shareAuthor: 'nemo',
  //   shareAuthorImg: '/img/user-4.jpg',
  //   sharedAt: new Date('2022-08-11'),
  //   shareDescription: 'share description',
  // },
  // {
  //   type: 'post',
  //   id: 'post1013449',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   description:
  //     '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
  //   media: [
  //     '/img/post-1.jpg',
  //     '/img/post-2.jpg',
  //     '/img/post-3.jpg',
  //     '/img/post-4.jpg',
  //     '/img/post-5.jpg',
  //     '/img/post-1.jpg',
  //     '/img/post-2.jpg',
  //     '/img/post-3.jpg',
  //     '/img/post-4.jpg',
  //     '/img/post-5.jpg',
  //     '/img/post-1.jpg',
  //     '/img/post-2.jpg',
  //     '/img/post-3.jpg',
  //   ],
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  //   shared: true,
  //   shareAuthor: 'nemo',
  //   shareAuthorImg: '/img/user-4.jpg',
  //   sharedAt: new Date('2022-08-11'),
  //   shareDescription: 'share description',
  // },
  // {
  //   type: 'post',
  //   id: 'post1013451',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   description:
  //     '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
  //   media: [
  //     '/img/post-1.jpg',
  //     '/img/post-2.jpg',
  //     '/img/post-3.jpg',
  //     '/img/post-4.jpg',
  //     '/img/post-5.jpg',
  //     '/img/post-6.jpg',
  //   ],
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  //   shared: true,
  //   shareAuthor: 'nemo',
  //   shareAuthorImg: '/img/user-4.jpg',
  //   sharedAt: new Date('2022-08-11'),
  //   shareDescription: 'share description',
  // },
  // {
  //   type: 'post',
  //   id: 'post1013452',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   description:
  //     '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
  //   media: [
  //     '/img/post-1.jpg',
  //     '/img/post-2.jpg',
  //     '/img/post-3.jpg',
  //     '/img/post-4.jpg',
  //     '/img/post-5.jpg',
  //     '/img/post-6.jpg',
  //   ],
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  // },
  // {
  //   type: 'blogPost',
  //   id: 'post1013450',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   title: 'blog post',
  //   article: blogPostText,
  //   media: ['/img/post-1.jpg'],
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  //   shared: true,
  //   shareAuthor: 'nemo',
  //   shareAuthorImg: '/img/user-4.jpg',
  //   sharedAt: new Date('2022-08-11'),
  //   shareDescription: 'share description',
  // },
  // {
  //   type: 'blogPost',
  //   id: 'post1013453',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   title: 'blog post',
  //   article: blogPostText,
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  //   shared: true,
  //   shareAuthor: 'nemo',
  //   shareAuthorImg: '/img/user-4.jpg',
  //   sharedAt: new Date('2022-08-11'),
  //   shareDescription: 'share description',
  // },
  // {
  //   type: 'post',
  //   id: 'post1013454',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   description:
  //     '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  //   shared: true,
  //   shareAuthor: 'nemo',
  //   shareAuthorImg: '/img/user-4.jpg',
  //   sharedAt: new Date('2022-08-11'),
  //   shareDescription: 'share description',
  // },
  // {
  //   type: 'post',
  //   id: 'post1013455',
  //   userName: 'daniel',
  //   userImg: '/img/user-1.jpg',
  //   description:
  //     '“Success is not final, failure is not fatal: it is the courage to continue that counts.”',
  //   comments: comments,
  //   createdAt: new Date('2022-07-26'),
  // },
  // {
  //   type: 'post',
  //   id: 'post1013456',
  //   userName: 'suzi',
  //   userImg: '/img/user-2.jpg',
  //   description: 'Squad means family and family means nobody gets left behind.',
  //   media: ['/img/post-2.jpg'],
  //   comments: comments,
  //   createdAt: new Date('2022-07-30'),
  // },
];

export const blogPosts = [
  {
    id: 'post701333',
    userName: 'nemo',
    userImg: '/img/user-4.jpg',
    title: 'blog post',
    article: blogPostText,
    media: [
      '/img/post-1.jpg',
      '/img/post-2.jpg',
      '/img/post-3.jpg',
      '/img/post-4.jpg',
      '/img/post-5.jpg',
      '/img/post-6.jpg',
      '/img/post-1.jpg',
      '/img/post-2.jpg',
      '/img/post-3.jpg',
      '/img/post-4.jpg',
      '/img/post-5.jpg',
      '/img/post-6.jpg',
      '/img/post-1.jpg',
      '/img/post-2.jpg',
      '/img/post-3.jpg',
      '/img/post-4.jpg',
      '/img/post-5.jpg',
      '/img/post-6.jpg',
    ],
    comments: comments,
    createdAt: new Date('2022-07-26'),
    shared: true,
    shareAuthor: 'nemo',
    shareAuthorImg: '/img/user-4.jpg',
    sharedAt: new Date('2022-08-11'),
    shareDescription: 'share description',
  },
  {
    id: 'post701333',
    userName: 'daniel',
    userImg: '/img/user-1.jpg',
    title: 'blog post',
    article: blogPostText,
    comments: comments,
    createdAt: new Date('2022-07-26'),
  },
  {
    id: 'post7013455',
    userName: 'suzi',
    userImg: '/img/user-2.jpg',
    title: 'blog post',
    article: blogPostText,
    media: ['/img/post-2.jpg'],
    comments: comments,
    createdAt: new Date('2022-07-30'),
  },
];

export const userInfo = {
  birthDate: '1990-09-11',
  birthPlace: {
    country: 'georgia',
    city: 'tbilisi',
  },
  livesIn: {
    country: 'georgia',
    city: 'tbilisi',
  },
  currentWorkPlace: {
    company: 'scandiweb',
    position: 'software engineer',
    from: '2015-08-07',
    to: '2022-08-19',
    description: 'great 5 year experience',
  },
  education: [
    {
      collage: 'itvet',
      faculty: 'Web-Interface and Graphical-Design',
      degree: 'bachelor',
      description: 'great 2 year experience',
      years: {
        from: '2019-09-16T00:00:00.000+00:00',
        to: '2021-07-26T00:00:00.000+00:00',
      },
    },
    {
      collage: 'TSU',
      faculty: 'Georgian Philology',
      degree: 'bachelor',
      description: 'great 4 year experience',
      years: {
        from: '2014-09-16T00:00:00.000+00:00',
        to: '2018-07-26T00:00:00.000+00:00',
      },
    },
  ],
  workplace: [
    {
      company: 'devsforworld',
      position: 'frontend-developer',
      description: 'great 3 year experience',
      workingYears: {
        from: '2017-03-13T00:00:00.000+00:00',
        to: '2020-06-16T00:00:00.000+00:00',
      },
    },
    {
      company: 'influencer',
      position: 'sofware-engineer',
      description: 'great 2 year experience',
      workingYears: {
        from: '2020-06-30T00:00:00.000+00:00',
        to: '2022-08-17T00:00:00.000+00:00',
      },
    },
  ],
  joinedAt: '2022-08-03',
};
